name: CD

on:
  release:
    types:
      - published

env:
  name: gandi-email

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            binary-ext: ""
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary-ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary-ext: ".exe"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: false
      - name: Move binary
        run: mv target/${{ matrix.target }}/release/$name${{ matrix.binary-ext }} .
      - name: Archive (tgz)
        run: tar -czvf $name-${{ matrix.target }}.tgz $name${{ matrix.binary-ext }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: $name-${{ matrix.target }}.tgz


